### ISSUE TITLE
provider: outlook

### ISSUE THREAD

**Issue by transitive-bullshit** [transitive-bullshit/puppeteer-email#1]
- [x] signin
- [ ] signup
- [ ] signout
- [ ] sendEmail
- [x] getEmails
- [ ] docs
- [ ] unit tests
- [ ] integration tests

**Comment by JonathanLehner** [comment]
doesnt work

**Comment by JonathanLehner** [comment]
with input puppeteer-email signup -u "test" -p "test" -P "outlook"
I get

{ ArgumentError: Expected `username` to be of type `string` but received type `undefined`
    at new GetSMSCodeClient (/usr/local/lib/node_modules/puppeteer-email-cli/node_modules/getsmscode/index.js:51:5)
    at new GetSMSCodeOTPProvider (/usr/local/lib/node_modules/puppeteer-email-cli/node_modules/sms-number-verifier/lib/provider-getsmscode.js:16:20)
    at Object.exports.getProviderByName (/usr/local/lib/node_modules/puppeteer-email-cli/node_modules/sms-number-verifier/lib/providers.js:16:10)
    at new SMSNumberVerifier (/usr/local/lib/node_modules/puppeteer-email-cli/node_modules/sms-number-verifier/index.js:22:19)
    at Command.program.command.option.option.option.option.action (/usr/local/lib/node_modules/puppeteer-email-cli/lib/cli.js:41:13)
    at Command.listener (/usr/local/lib/node_modules/puppeteer-email-cli/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/puppeteer-email-cli/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/puppeteer-email-cli/node_modules/commander/index.js:474:21) name: 'ArgumentError' }

**Comment by mvanaltvorst** [comment]
Still working on this, @transitive-bullshit?

**Comment by transitive-bullshit** [comment]
My efforts are focused on [Saasify](https://github.com/saasify-sh/saasify) these days.

PRs are more than welcome, though 🙏
